### ISSUE TITLE
Could not open .../round-2/families.stk for reading!

### ISSUE THREAD

**Issue by oushujun** [rmhubley/RepeatModeler#1]
I was trying to use this new version but there is an error at round-2. The last several lines of the STDOUT are shown below:

Comparison Time: 00:00:13 (hh:mm:ss) Elapsed Time, 561 HSPs Collected
  - RECON: Running imagespread..
RECON Elapsed: 00:00:00 (hh:mm:ss) Elapsed Time
  - RECON: Running initial definition of elements ( eledef )..
RECON Elapsed: 00:00:00 (hh:mm:ss) Elapsed Time
  - RECON: Running re-definition of elements ( eleredef )..
RECON Elapsed: 00:00:00 (hh:mm:ss) Elapsed Time
  - RECON: Running re-definition of edges ( edgeredef )..
RECON Elapsed: 00:00:00 (hh:mm:ss) Elapsed Time
  - RECON: Running family definition ( famdef )..
RECON Elapsed: 00:00:00 (hh:mm:ss) Elapsed Time
  - Obtaining element sequences
Number of families returned by RECON: 262
Processing families with greater than 15 elements
Could not open /mnt/tiger/osj/TE/Selaginella/S_lep_V4.2/RepeatModeler2/RM_46181.ThuMay111045252017/round-2/families.stk for reading!

In the round-2 directory, there was no families.stk file, but in the parent directory I could see the file families.stk was created and data were dumped in it.
I think the bug lies around line 534 in RepeatModeler where the directory of families.stk is assigned:
 my $combFamiliesFile  = "$tmpDir/families.stk";
But it was a bit complicated for me to debug it.

The dependent program versions:
RepeatMasker/4.0.6
RMBLAST/2.6.0
RECON/1.08
trf404.linux64
RepeatScout/1.0.5

I also installed RepeatModeler/1.0.8 and it worked well with the above dependent programs.

**Comment by rmhubley** [comment]
Thanks for the report.  You are correct.  There is a bug in the code that is exercised when no repeats are detected in a round.  I have patched the MASTER branch and will make a release shortly.
