### ISSUE TITLE
RepeatMasker.lib.[n??] doesn't exist!

### ISSUE THREAD

**Issue by mahulchak** [rmhubley/RepeatModeler#10]
Hi,
I am using the configure script to configure the software and I am getting the following warning at the end:

WARNING: /data/apps/user_contributed_software/mchakrab/RepeatMasker/Libraries/RepeatMasker.lib.[n??] doesn't
        exist!  RepeatModeler will not run correctly without these
        files.  Please re-run /data/apps/user_contributed_software/mchakrab/RepeatMasker/configure to create
        these files automatically.  Then re-run this script.

However, the current version of RepeatMasker (4.0.7) has an empty RepeatMasker.lib file, which does not seem to interfere with the RepeatMasker run. Is it happening because the RepeatMasker.lib file is no longer used by Repeatmasker ?

**Comment by rmhubley** [comment]
When you installed RepeatMasker did you download and install either RepBase ( RepeatMasker Edition ) or Dfam_consensus before running configure?

**Comment by mahulchak** [comment]
Yes. And running configure somehow erased the content of the RepeatMasker.lib file. I (seemingly) solved the issue by doing this:
I copied the RepeatMasker.lib file manually from the RepeatMasker folder before running configure. Then after running configure, I restored the RepeatMasker.lib file and ran makeblastdb on it. RepeatModeler installed fine after this.

**Comment by mahulchak** [comment]
Yes I installed RepBase before running configure.

**Comment by rmhubley** [comment]
I haven't seen this behavior before nor can I reproduce this effect.  Configure converts the libraries downloaded from RepBase ( RepBase RepeatMasker Edition file RMRBSeqs.embl ), and/or the Dfam_consensus ( DfamConsensus.embl ) into an EMBL file called RepeatMaskerLib.embl which is later used to create the FASTA file RepeatMasker.lib.  I suspect that one of your downloaded libraries was corrupted and configure couldn't parse the input files.

**Comment by mahulchak** [comment]
If you are unable to reproduce the error, then it is probably something on my side. Many thanks for looking into it.

**Comment by rmhubley** [comment]
I don't believe this is a bug in the program although we could do better at hand holding/automating the library installation process.

**Comment by FredMasc** [comment]
It seems to be a reproducible bug. I got exactly the same error.

**Comment by rbatorsky** [comment]
I encountered this error today when trying to configure RepeatMasker and RepeatModler for use with funannotate fungal genome annotation pipeline.  I downloaded the newest version of RepBase  for RepeatMasker and was trying to configure it with older versions of the rest of the libraries.  The resulting RepeatMasker.lib was empty. When I downgraded to the same version of RepBase for RepeatMasker (which in this case was RepBaseRepeatMaskerEdition-20170127.tar.gz) the library got created.

**Comment by Jorisvansteenbrugge** [comment]
I experienced the same issue, however, I discovered that it only occurred if I was trying to use the latest RepBase library on the non-latest version (open-4-0-7) of RepeatMasker. When using version 4-0-8 of RepeatMasker the problem was solved.

**Comment by Biscuite-wzy** [comment]
I have the same error:
 /home/zy/biosoft/RepeatMasker/Libraries/RepeatMasker.lib.[n??] doesn't exist!  RepeatModeler will not run correctly without these files.  Please re-run /home/zy/biosoft/RepeatMasker/configure to create these files automatically.  Then re-run this script.

**Comment by jebrosen** [comment]
@Biscuite-wzy could you open a new issue including more of the details listed in the template? Especially important is the program version and libraries you have installed/configured and how you installed it.
