### ISSUE TITLE
No families identified

### ISSUE THREAD

**Issue by pgonzale60** [rmhubley/RepeatModeler#19]
Hello,

I want to identify novel repeat families in nematode genomes. I use RepeatModeler for this, but it finishes saying "No families identified.  Perhaps the database is too small..." [RMIII.log](https://github.com/rmhubley/RepeatModeler/files/2533125/RMIII.log).
I ran RepeatModeler on a fasta with the first 4000000 bases of chromosome III (`samtools faidx III:1-4000000 c_elegans.PRJNA13758.WS261.genomic.fa`) from C. elegans (ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/sequence/genomic/c_elegans.PRJNA13758.WS261.genomic.fa.gz).
I have previously run it on the complete genome using 22 cores. It took around 42 hours, but it similarly was unable to identify any family.
I installed RepeatModeler using `conda install -c bioconda repeatmodeler`. [This](https://github.com/rmhubley/RepeatModeler/files/2533127/pg_repeatmodeler.yml.txt) is my environment.

What should I do differently to identify novel repeats?

Bests,
Pablo

**Comment by JennyHTLee** [comment]
Hi Pablo,

The bioconda recipe for repeatmodeler is not fully functional, I suggest that you check if all the dependencies are working http://www.repeatmasker.org/RepeatModeler/, and that the paths to each of these dependencies are correct in "RepeatMaskerConfig.pm" and "RepModelConfig.pm".
(To be sure, I actually ended up installing all the dependencies from source.)

Cheers,
Jenny

**Comment by pgonzale60** [comment]
Hi Jenny,

Thank you! Indeed, installing from source solved the issue. The problem is then not in RepeatModeler, but the bioconda recipe. So I close this issue.

Best wishes,
Pablo
