### ISSUE TITLE
TRF not found during configuration

### ISSUE THREAD

**Issue by pig-raffles** [rmhubley/RepeatModeler#20]
I previously installed RepeatModeler using Conda and whilst the program ran through to completion, I got the same error message as seen in issue #15 

I am now trying to install Repeat modeler and all its dependent programs myself. When running the configure script for RepeatModeler, it does not recognize the TRF file that is present (despite it being executable), giving the message "does not appear to contain the trf program". 

Apologies if there is a simple solution to this but I can't get configuration completed without this.

Thanks for any advice you can give

**Comment by coreywischmeyer** [comment]
I just successfully installed RepeatModeler and I had to rename the executable that was named: trf<version>.linux64 to trf for it to work.

**Comment by pig-raffles** [comment]
Thanks! That worked perfectly

**Comment by rmhubley** [comment]
The error message should have indicated that it was looking for executable file called "trf".  It is bizarre that the TRF developers do not keep the name of the executable the same between platforms and suffix it with the architecture.  In any case, I am about to release a new RepeatMasker ( and soon a new RepeatModeler ).  In both cases I will make the configure script look for all possible TRF suffixes.
