### ISSUE TITLE
`recoverDir` option doesn't appear to work

### ISSUE THREAD

**Issue by zrlewis** [rmhubley/RepeatModeler#21]
Hi-

I had a a RepeatModeler (`version DEV`) job time out and I am trying to restart using this command:

```
RepeatModeler -pa 16 -recoverDir RM_28668.SunJan131256362019 -database repeatDB >& repeatModel_restart3.out
```

However, `RM` doesn't seem to recognize completed rounds in the directory. Here's the error:

```
RepeatModeler Version DEV
================================
Search Engine = ncbi
Random Number Seed: 1547740043
Database = repeatDB ......
  - Sequences = 54313
  - Bases = 2854780185


Oops...the ./RM_28668.SunJan131256362019 run did not get passed round-1.
It makes more sense to restart this run from the beginning.
Remove the -recoverDir option and rerun the program.
```

Yet there are completed rounds in the directory. See below:
```
ls ./RM_28668.SunJan131256362019
consensi.fa  families.stk  round-1  round-2  round-3  round-4  round-5
```

Any ideas on how to get the job restarted while recognizing completed rounds?

Thanks!
Zack

**Comment by rmhubley** [comment]
The DEV release is not meant to be run by users -- it's the active development branch of RepeatModeler.  What you want is the latest release from the "releases" link instead.

**Comment by rmhubley** [comment]
I misspoke about the "DEV" release.  If you did, in fact download this release from the RepeatMasker website or from the "releases" link on github then you may have the full released version.  I just realized that during our switch from CVS to GIT the RepeatMasker & RepeatModeler version designation was incorrectly set.  

Back to your issue.  The way RepeatModeler determines if a round completed is to look for particular files in each of the round directories:

   - round-1/consensi-refined.fa  or, if this file 
           is empty/missing it looks for round-1/sampleDB-1/fa.rscons.filtered
   - round-2/consensi.fa
      ...
   - round-n/consensi.fa

Are these files there and non-empty?

**Comment by rmhubley** [comment]
Right...so this looks like Round-1 didn't even complete.  The directory doesn't contain the "consensi-refined.fa" and the sampleDB-1.fa.rscons.filtered is empty.  I suspect there is something strange with the round-1/sampleDB-1.fa.rscons file.  If you send me that file I could take a look further.  The bottom line is that it failed on the first step so even if we find the problem, the recover mechanism is still going to have to start from the very beginning as it can only go back to the previous successful round.

**Comment by Juke34** [comment]
Hi I have exactly the same problem. Wanted to resume a job (stopped due to time limit). Apparently it was working on round 6 when it stopped but when I try to resume I get this messge: `Oops...the /scratch/jacda119/RM_12063.FriNov291313512019 run did not get passed round-1`

In the round1 folder I have: 
```
-rw-rw-r-- 1 jacda119 jacda119 45093970 Nov 29 13:18 sampleDB-1.fa
-rw-rw-r-- 1 jacda119 jacda119 73244770 Nov 29 13:18 sampleDB-1.fa.lfreq
-rw-rw-r-- 1 jacda119 jacda119  1454634 Nov 29 13:24 sampleDB-1.fa.rscons
-rw-rw-r-- 1 jacda119 jacda119        0 Nov 29 13:24 sampleDB-1.fa.rscons.filtered
```

In the subsequent round (2 to 6 ) the consensi.fa file is empty.

I use RepeatModeler version open-1.0.8.
Here is the sampleDB-1.fa.rscons file from round1.
[sampleDB-1.fa.rscons.zip](https://github.com/Dfam-consortium/RepeatModeler/files/3922483/sampleDB-1.fa.rscons.zip)

**Comment by jebrosen** [comment]
@Juke34 How did you install and configure RepeatScout and RepeatModeler? Is the path you configured for RepeatScout missing the program `filter-stage-1.prl`?

**Comment by Juke34** [comment]
I use repeatmodeler 1.0.8 from bioconda.
There is RepeatScout in the path but nothing called `filter-stage-1.prl`.

**Comment by jebrosen** [comment]
Yes, the bioconda package is broken - in particular that issues looks like bioconda/bioconda-recipes#9988.

For this reason we still recommend manual installation (http://www.repeatmasker.org/RepeatModeler/), or out new containerized version that is suitable for some users (https://github.com/Dfam-consortium/TETools).

**Comment by Juke34** [comment]
I need Conda recipe, I will try to fix it. thank you for your help.

**Comment by Juke34** [comment]
I have fixed the Conda recipe, now `filter-stage-1.prl is accessible in the path but my output is still the same 

```-rw-rw-r-- 1 jacda119 jacda119 44977382 Dec  6 09:54 sampleDB-1.fa
-rw-rw-r-- 1 jacda119 jacda119 72311486 Dec  6 09:54 sampleDB-1.fa.lfreq
-rw-rw-r-- 1 jacda119 jacda119  1419475 Dec  6 10:01 sampleDB-1.fa.rscons
-rw-rw-r-- 1 jacda119 jacda119        0 Dec  6 10:01 sampleDB-1.fa.rscons.filtered```

any idea?
