### ISSUE TITLE
Input file format, and syntax

### ISSUE THREAD

**Issue by anandksrao** [rmhubley/RepeatModeler#23]
For input file, can the genome multifasta file be
**1.** formatted to contain alternating lines of headers and sequences?
**2.** Does the header need to be necessarily in gi|xxx or some other 'required' format?

For syntax, while running multiple genomes as array job on a SLURM scheduler, can I
**3.** omit using nohup?
**4.** not use recommended redirection >& run.out &, but a more simple syntax version that reads:
RepeatModeler -engine ncbi -pa 3 -database elephant > run.out ?

**Comment by rmhubley** [comment]
The input file is expected to be in FASTA format, single or multiple sequences and with no restriction on the identifier used as long as it's unique within the file.

If you run on a cluster through a job scheduler you will not need the nohup prefix -- that was just placed there as a suggestion in the example run.  That also applies to the redirection as most job schedulers automatically capture stdout/stderr to files.
