### ISSUE TITLE
Run errors with blastdbcmd - how to fix BuildDatabase step error?

### ISSUE THREAD

**Issue by anandksrao** [rmhubley/RepeatModeler#24]
My RepeatModeler runs use new versions of RepeatModeler and it's dependencies on a UBUNTU-based HPCC, and a SLURM queue management system. Their versions are:

`slurm/18.08.3,  openmpi/3.1.2(default), perlbrew/5.16.0, trf/4.09, hmmer/3.2.1, rmblast/2.6.0, crossmatch/1.090518, abblast/4Jan2019, repeatmasker/4.0.8, recon/1.08, repeatscout/1.0.5 and repeatmodeler/1.0.11`

For my array job with ~40 individual genome multifasta files, I see the following errors:

Only 2 of the array jobs exited prematurely, another 7 have been running for ~ 75 minutes now. 
STDERR files for both failed jobs indicated errors with such lines:
```
Error: [blastdbcmd] Entry not found: 10
Error: [blastdbcmd] Entry not found: 1
Error: [blastdbcmd] Entry or entries not found in BLAST database
Error: [blastdbcmd] Entry or entries not found in BLAST database
RepeatModeler::sampleFromDB() Could not obtain sequence ( entry = 1, start = 16440001 end = 16480000 ) from the database!
RepeatModeler::sampleFromDB() Could not obtain sequence ( entry = 10, start = 15160001 end = 15200000 ) from the database!
```

They way I set up my runs, outputs for both steps should be in same folder.

Output folder contents look like so:
total 29M
```
-rw-rw-r-- 1 aksrao aksrao  790 Mar 19 14:58 Ath_RepeatModeler.out
drwxrwxr-x 3 aksrao aksrao 4.0K Mar 19 14:58 RM_14990.TueMar191458462019
drwxrwxr-x 3 aksrao aksrao 4.0K Mar 19 14:58 RM_14991.TueMar191458462019
-rw-rw-r-- 1 aksrao aksrao   56 Mar 19 14:58 Ath_RepeatModeler.nnd
-rw-rw-r-- 1 aksrao aksrao  29M Mar 19 14:58 Ath_RepeatModeler.nsq
-rw-rw-r-- 1 aksrao aksrao  252 Mar 19 14:58 Ath_RepeatModeler.nhr
-rw-rw-r-- 1 aksrao aksrao  168 Mar 19 14:58 Ath_RepeatModeler.nin
-rw-rw-r-- 1 aksrao aksrao   49 Mar 19 14:58 Ath_RepeatModeler.translation
```

This folder, for one of the failed array jobs, is missing *.nni and *.nog files, right?
Is this a problem with BuildDatabase step? How can I prevent this?

In another folder, for the other failed array job, it is missing just one file - the *.nog file (not shown here).

In this folder, the *.out output file contents are as follows:
```
cat Ath/Ath_RepeatModeler.out 
RepeatModeler Version open-1.0.8
================================
Search Engine = ncbi
Database = Ath_RepeatModeler .
  - Sequences = 7
  - Bases = 119667750
RepeatModeler Version open-1.0.8
================================
Search Engine = ncbi
Database = Ath_RepeatModeler .
  - Sequences = 7
  - Bases = 119667750
Using output directory = /home/aksrao/PhytozomeV12/RepeatModeler/Ath/RM_14991.TueMar191458462019


RepeatModeler Round # 1
========================
Searching for Repeats
 -- Sampling from the database...
Using output directory = /home/aksrao/PhytozomeV12/RepeatModeler/Ath/RM_14990.TueMar191458462019


RepeatModeler Round # 1
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 40000000 bp
   - Gathering up to 40000000 bp
```

Deeper folder structure in the output folder reveals 2 folders, both with an empty file each
 ls -lh */*
```
RM_14990.TueMar191458462019/round-1:
total 0
-rw-rw-r-- 1 aksrao aksrao 0 Mar 19 14:58 sampleDB-1.fa

RM_14991.TueMar191458462019/round-1:
total 0
-rw-rw-r-- 1 aksrao aksrao 0 Mar 19 14:58 sampleDB-1.fa

```

Is there a problem with RepeatModeler step also?

Does any / all of these bits of info help diagnose where the problem(s) may be? 

Thanks for your help!

**Comment by rmhubley** [comment]
I need more info to help with this.  Have you checked that the FASTA files for these two failed jobs looks correct:  
  - Independent lines for identifiers and sequences
  - Sequence contains valid DNA codes ACGT and IUB codes RYKMSWBDHVN  only?

You can also try re-running the BuildDatabase script for those failed runs and post the full output here.

-R

**Comment by rmhubley** [comment]
Please let me know if this is still an issue for you.  I would also recommend updating to the latest RepeatModeler version 1.0.11
