### ISSUE TITLE
Running on mammalian de novo assembly genome for a week 

### ISSUE THREAD

**Issue by Lesdormis** [rmhubley/RepeatModeler#25]
Hi there,

I am trying to use the RepeatModeler for a de novo assembly mammalian genome to build the repeat model and then use the RepeatMask to mask the repeat region. The issue is the program has been running in our slurm HPC for almost a week? Is that normal?

#!/bin/bash
#SBATCH --job-name=modl
#SBATCH --partition=cpu_short
#SBATCH --nodes=1
#SBATCH --mem=64gb
#SBATCH --mem-per-cpu=6gb
#SBATCH --time=596:00:00
#SBATCH --cpus-per-task=1

perl BuildDatabase -name genome -engine fastafile
nohup ./RepeatModeler -engine ncbi -pa 3 -database genome >& run3.out

**Comment by Lesdormis** [comment]
And right now is in its round 6.

RepeatModeler Round # 6
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 100000000 bp
 -- Running TRFMask on the sequence...
       27354 Tandem Repeats Masked
 -- Masking repeats from the previous rounds...
  - Masking 1 - 5 of 2722
  - Masking 16 - 30 of 2722

   35% completed,  46:38:30 (hh:mm:ss) est. time remaining.


I am wondering how many rounds are it needed?

**Comment by rmhubley** [comment]
This will be the last round, but you can always use the output that has been obtained thus far.  The question is not easy to answer as it depends greatly on the data it's given.   On an average computer it could take a week to do the large all-vs-other searches for a repeat-poor genome.  For a repeat rich-genome it often goes much faster as more of the sequence is masked by repeats from previous rounds before the all-vs-other runs are started.  I typically peek at the current consensi.fa ( e.g RM_1623.ThuMay311504r482018/consensi.fa ) as RM is running to get a sense for what has been found so far.  It's also good to keep an eye on how much of the sample for a round is masked by the repeats from previous rounds as this will give you an idea of how much the coverage the library can achieve already.  Does that help?

**Comment by rmhubley** [comment]
I am closing this for now.  If you continue to have problems please let me know.
