### ISSUE TITLE
build_lmer_table failed. Exit code -1

### ISSUE THREAD

**Issue by LliliansCalvo** [rmhubley/RepeatModeler#27]
Hi, 
I am trying to run RepeatModeler in a cluster and I keep getting this error:
**build_lmer_table failed. Exit code -1**

RepeatModeler Version DEV
================================
Search Engine = ncbi
Random Number Seed: 1554200830
Database = Phaw_reference ............................
  - Sequences = 278189
  - Bases = 2752560740
Using output directory = /net/lustre/mqbpwlc2/repeatmask/RM_377397.TueApr21127322019

RepeatModeler Round # 1
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 40000000 bp
   - Final Sample Size = 49721210 bp ( 40020098 non ambiguous )
   - Num Contigs Represented = 5537
 -- Running RepeatScout on the sequences...
   - RepeatScout: Running build_lmer_table ( l = 14 )..

I do get an output folder but for some reason the program stops running after round1. 
Could you point me out in the right direction ?

Thanks

**Comment by rmhubley** [comment]
I wonder if this is a memory issue with this system.  One thing you can try is to lower the sample size for RepeatScout by changing line ~250 of the RepeatModeler script:

From:

```
my $rsSampleSize               = 40000000;     # The size of the sequence given
                                                                          #   to RepeatScout. ( round #1 )
```

To:

```
my $rsSampleSize               = 40000000;     # The size of the sequence given
                                               #   to RepeatScout. ( round #1 )
````

**Comment by rmhubley** [comment]
Closing this for now.  Let me know if this continues to be an issue.

**Comment by mdebiasse** [comment]
Good afternoon,
I am getting a similar error message with version 2.0.1 (full out file below):

`build_lmer_table failed. Exit code 35072`

I am running the program with singularity. As I understand it, I can't access the scripts outside of the environment since the script builds the environment on the fly and there is no static image being deployed or recalled. Therefore, Im not sure how to access the RepeatModeler script for editing outside of the environment. Any advice is appreciated!

```
Docker image path: index.docker.io/dfam/tetools:1.3.1
Cache folder set to /home/mdebiasse/.singularity/docker
Creating container runtime...
RepeatModeler Version 2.0.1
===========================
Search Engine = rmblast 2.11.0+
Dependencies: TRF 4.09, RECON 1.08, RepeatScout 1.0.5, RepeatMasker 4.1.2
LTR Structural Analysis: Disabled [use -LTRStruct to enable]
Random Number Seed: 1619459304
Database = /mnt/derm .
  - Sequences = 22
  - Bases = 370782577
Using output directory = /home/mdebiasse/RM_1924.MonApr261749552021
Storage Throughput = poor ( 108.07 MB/s )
  - NOTE: Poor storage througput will have a large impact on RepeatModeler
          performance.  The low throughput observed above may be due to
          transient usage patterns on the system and may not reflect the
          actual system performance. Whenever possible run RepeatModeler
          in a directory stored on a fast local disk and not over a
          network filesytem.

Ready to start the sampling process.
INFO: The runtime of RepeatModeler heavily depends on the quality of the assembly
      and the repetitive content of the sequences.  It is not imperative
      that RepeatModeler completes all rounds in order to obtain useful
      results.  At the completion of each round, the files ( consensi.fa, and
      families.stk ) found in:
      /home/mdebiasse/RM_1924.MonApr261749552021/
      will contain all results produced thus far. These files may be
      manually copied and run through RepeatClassifier should the program
      be terminated early.


RepeatModeler Round # 1
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 40000000 bp
   - Final Sample Size = 40037417 bp ( 40033117 non ambiguous )
   - Num Contigs Represented = 22
   - Sequence extraction : 00:04:10 (hh:mm:ss) Elapsed Time
 -- Running RepeatScout on the sequences...
   - RepeatScout: Running build_lmer_table ( l = 14 )..
build_lmer_table failed. Exit code 35072
slurmstepd: error: Detected 1 oom-kill event(s) in step 2092087.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```
