### ISSUE TITLE
FastaDB::getSubstr - Error index out of bounds!

### ISSUE THREAD

**Issue by SvitlanaLukicheva** [rmhubley/RepeatModeler#28]
Hello,

After several days of execution, RepeatModeler failed with the following error message: "FastaDB::getSubstr - Error index out of bounds!". This problem was already described several times on different forums, for example:
- [Biositar](https://www.biostars.org/p/71521/)
- [SEQanswers](http://seqanswers.com/forums/showthread.php?t=25832)
and it seems that the only solution is to launch RepeatModeler several times until it succeeds.

Is there any other solution to this problem?

Thank you in advance!

**Comment by rmhubley** [comment]
These are hard to track down as they typically originate deep within the RECON codebase and the author no longer supports the package.  The reason why it often works for people when they try rerunning is that RepeatModeler uses a random sampling from the genome.  By rerunning ( and not using the -seed option ) you will most likely get a different sample to analyze thus avoiding whatever bug lurks in RECON.  If you have the full RepeatModeler output for this run I could have a look at it and see if I can reproduce the failure.

**Comment by SvitlanaLukicheva** [comment]
Thank you for your explanation!
I didn't keep the intermediate files generated by RepeatModeler, but I attach here the output produced by the program. If you need the other files I will send them the next time the program crashes (if it crashes!)
[repeat_modeler.txt](https://github.com/rmhubley/RepeatModeler/files/3048161/repeat_modeler.txt)

**Comment by rmhubley** [comment]
Thanks for the log file.  While it doesn't help track down the problem without the intermediate files ( in this case the directory RM_20454.WedApr30158522019 ) it does indicate that it processed quite a bit of your genome and was almost finished ( last round is Round-6 in this run with a 100MB sample ).  The round-5 results alone masked over 64% of this final sample which is quite good.  I should point out that if this happens again, you can always use the results obtained before the crash.  In this case a the round-1-5 results would have been in the RM_204*/consensi.fa and consensi.stk files.  Do let me know if you see this error again.

**Comment by rmhubley** [comment]
At the start of each round RepeatModeler writes the following to the screen:

```
 -- Running TRFMask on the sequence...
       151 Tandem Repeats Masked
 -- Masking repeats from the previous rounds...
  - Masking 1 - 5 of 90
  - Masking 16 - 30 of 90
  - Masking 41 - 65 of 90
  - Masking 76 - 90 of 90
 -- Sample Stats:
       Sample Size 3600000 bp
       Num Contigs Represented = 1
       Non ambiguous bp:
             Initial: 3019425 bp
             After Masking: 2010285 bp
             Masked: 33.42 % 
```

The last line above is indicates that repeats found in the previous round + TRF were able to mask 33.42 of the new sample taken from the genome.

-R
