### ISSUE TITLE
RepeatClassifier thread option

### ISSUE THREAD

**Issue by PlantDr430** [rmhubley/RepeatModeler#30]
Hello,

I just wanted to confirm that there is not parallel threading option for RepeatClassifier. If so, is there a reason this is not an option?

**Comment by rmhubley** [comment]
Not at this time.  We are re-focusing our efforts on this package and I will add this to the list of feature requests.  Since the search phase of RepeatModeler is the slowest step, we are initially focusing on making this phase work on clusters as well as using the current threading model.
