### ISSUE TITLE
perl modules  JSON

### ISSUE THREAD

**Issue by LliliansCalvo** [rmhubley/RepeatModeler#31]
Hi, 
I have installed JSON on my computer but I am still getting this error when I try to run perl ./configure
The following perl modules required by RepeatModeler are missing from
your system.  Please install these first:
    JSON
Could you guide me towards the solution?

Thanks !

**Comment by Ramkyeri** [comment]
Hai I am also getting same problem

**Comment by jebrosen** [comment]
Hello @Ramkyeri,

The `JSON` perl module is available in many package repositories by a name such as `perl-json` or `libjson-perl`. Or, the `JSON` module can be installed from CPAN.
