### ISSUE TITLE
RepeatScout compile warnings

### ISSUE THREAD

**Issue by EugeneKim76** [rmhubley/RepeatModeler#33]
Deal all,
I recently installed RepeatScout, 
However, after "make" command, many warnings were shown as below.
According to the README file of RepeatScout,  the software should build with no errors or warnings.
Hence, I made effort to remove those warnings, however, failed.
Although I installed with warnings below, RepeatModeler produced consensi sequences without any error.
Is there anyone installed RepeatScout with warnings shown below?
Is there any problem to ignore those warnings?

Best

build_repeat_families.c: In function ‘main’:
build_repeat_families.c:137:36: warning: value computed is not used [-Wunused-value]
   co_get_int(argc, argv, "-l", &l) || (l = default_l(MAXLENGTH));
                                    ^
build_repeat_families.c:161:62: warning: value computed is not used [-Wunused-value]
   co_get_float(argc, argv, "-maxentropy", &MAXENTROPY)       || (MAXENTROPY=-0.7);
                                                              ^
build_repeat_families.c:174:19: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   master[2*L+l] = (char)NULL;
                   ^
build_repeat_families.c: In function ‘mask_headptr’:
build_repeat_families.c:1026:28: warning: variable ‘flip’ set but not used [-Wunused-but-set-variable]
   int x, y, smallh, h, h2, flip;
                            ^
build_repeat_families.c: In function ‘build_headptr’:
build_repeat_families.c:389:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf(fp,"%s",string);
     ^
build_repeat_families.c:390:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf(fp,"%d",&thisfreq);
     ^
build_repeat_families.c:391:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf(fp,"%d",&thisocc);
     ^
cc -O3 -Wall -c cmd_line_opts.c -o cmd_line_opts.o 
cc -O3 -Wall -c version.c -o version.o 
cc build_repeat_families.o cmd_line_opts.o version.o -o RepeatScout -lm
cc -O3 -Wall -c build_lmer_table.c -o build_lmer_table.o 
build_lmer_table.c: In function ‘main’:
build_lmer_table.c:85:36: warning: value computed is not used [-Wunused-value]
   co_get_int(argc, argv, "-l", &l) || (l = default_l(MAXLENGTH));
                                    ^
build_lmer_table.c:51:10: warning: variable ‘start’ set but not used [-Wunused-but-set-variable]
   time_t start;
          ^
cc build_lmer_table.o cmd_line_opts.o version.o -o build_lmer_table -lm

**Comment by jebrosen** [comment]
> According to the README file of RepeatScout, the software should build with no errors or warnings.

As far as I can tell the README was last updated in 2008, so I am not surprised that compilers have implemented new warnings since then. Most of these warnings are harmless, and the ones that aren't are very unlikely to be a problem in practice.

We will coordinate with the appropriate people and teams to fix these warnings in a future version.

**Comment by EugeneKim76** [comment]
Thanks for kind reply.
I will add comments about this issue later when I have a better understanding of those warings.
Best
