### ISSUE TITLE
Link 404 forRECON-1.08.tar.gz 

### ISSUE THREAD

**Issue by Botantisty** [rmhubley/RepeatModeler#42]
Hello, 

I'am currently attempting to install and I note that the link provided for RECON-1.08.tar.gz with bug fixes is not currently working.

Thanks,
Sara Martin

**Comment by rmhubley** [comment]
Could you try it again?  I just tried to download it and the link worked for me:

[http://www.repeatmasker.org/RepeatModeler/RECON-1.08.tar.gz](http://www.repeatmasker.org/RepeatModeler/RECON-1.08.tar.gz)

**Comment by Botantisty** [comment]
Hello,

Your link works for me, but the one in the read me (http://www.repeatmasker.org/RECON-1.08.tar.gz) does not.  It looks like the path has changed. 

Thank you.

**Comment by rmhubley** [comment]
Oh...thanks!  I'll get that corrected.

**Comment by Qbgg** [comment]
Hello, now it seems the link of RECON-1.08 do not work again, with a 404 webpage saying 'The requested URL was not found on this server'. I think it maybe an issue same as above.

**Comment by pasviber** [comment]
Hi, the same happens to me.

**Comment by elcortegano** [comment]
Search for it in the RepeatMasker site. The link [http://www.repeatmasker.org/RECON-1.08.tar.gz](http://www.repeatmasker.org/RECON-1.08.tar.gz) works

**Comment by Qbgg** [comment]
> Search for it in the RepeatMasker site. The link http://www.repeatmasker.org/RECON-1.08.tar.gz works

Thanks! I had successfully isntalled and run RepeatModeler by annaconda, thanks for your help again!
