### ISSUE TITLE
WUBlast error ; ABBlast, rmblast  or ncbi blast?

### ISSUE THREAD

**Issue by ViriatoII** [rmhubley/RepeatModeler#43]
Hey,

I'm a bit overwhelmed with all of this. I installed RepeatModeler with abblast. I get the following error when I run RepeatModeler:

>ERROR from search engine (4)      
       99% completed,  00:0:00 (hh:mm:ss) est. time remaining.     
WUBlastSearchEngine::search: FATAL:  Segmentation Violation signal received.

>Discovery complete: 0 families found
Program Time: 00:36:27 (hh:mm:ss) Elapsed Time
Working directory:  /gpfs/project/projects/qggp/C34_PS/experiments/annotation/maker/d_tenuifolia/RM_55045.TueSep31455132019
may be deleted unless there were problems with the run.
No families identified.  Perhaps the database is too small
or contains overly fragmented sequences.

What's wrong? And an important question, what is better, ABBlast or rmblast (patched ncbi blast) ?
I see everyone using the second but I am struggling to install it...

Cheers,
Ricardo

**Comment by jebrosen** [comment]
> > WUBlastSearchEngine::search: FATAL: Segmentation Violation signal received

Unfortunately tracking down this kind of error would take some work. What version of AB-Blast/WU-Blast did you try?

> And an important question, what is better, ABBlast or rmblast (patched ncbi blast) ? I see everyone using the second but I am struggling to install it...

It is usually easier for us to provide support for RMBlast. What issues have you experienced with installing it?

**Comment by rmhubley** [comment]
I also do not recognize the "BuildModeler" command, was that a typo?

**Comment by ViriatoII** [comment]
Thank you for the prompt attention! Here are my answers:

> I also do not recognize the "BuildModeler" command, was that a typo?

Oh, yes, sorry. I meant RepeatModeler command (editing the post as well)

>Unfortunately tracking down this kind of error would take some work. What version of AB-Blast/WU-Blast did you try?

I tried AB-BLAST 3.0 [RELEASE 2019-01-04], which I believe is the latest. I just downloaded from their page a couple of weeks ago, registering beforehand.

>It is usually easier for us to provide support for RMBlast. What issues have you experienced with installing it?

rmblast takes a huge time compiling and created the binaries. However, configuring RepeatModeller with it gives an error saying that the full RepBase libraries for RepeatMasker are necessary, asking to download them and to retry configuring. 

I cannot download those libraries, it asks me to pay 1,200 euros. That is why I tried ABBlast first. 

I am now trying to run repeatmodeler with ncbi engine and it is doing things, even though its configuration gave that error.
(a new error in the ncbi run, in ncResults-1252.err :  "BLAST failed to write output" )

**Comment by rmhubley** [comment]
In general there shouldn't be any difference between using RMBlast and ABBlast with RepeatModeler/RepeatMasker.  Also, the message you saw indicating you do not have a "complete" database when installing RepeatMasker is a bit outdated.  Before RepBase became a subscription-based resource and RepeatMasker didn't have any alternative libraries we recommended users download it.  Now RepeatMasker comes with Dfam a growing open-database of TE families, and is sufficient for the tasks RepeatModeler requires of it.  

In terms of installation time, RMBlast now is distributed in binary form so you do not have to compile it yourself.  They are available at: http://www.repeatmasker.org/RMBlast.html

Now that I said there shouldn't be a difference between ABBlast/RMBlast I am going to contradict myself:  In the case of the most recent versions of ABBlast we haven't had a chance to test them with RepeatMasker/RepeatModeler.  I suspect there are some changes recent changes to ABBlast that are incompatible.  This is something we intend to fix in an upcoming release.  For now I recommend you use RMBlast.

**Comment by ViriatoII** [comment]
Thank you! It's working well. Have a great day!
