### ISSUE TITLE
rmblast make[1]: *** [install-toolkit] Error 1 on RHEL 7.3

### ISSUE THREAD

**Issue by ponomarevsy** [rmhubley/RepeatModeler#5]
Hello! I am using RHEL 7.3 and the latest release of RMBlast, ncbi-blast-2.6.0+-src.tar.gz, with patch isb-2.6.0+-changes-vers2.patch.gz as described here:

http://www.repeatmasker.org/RMBlast.html and I am getting the following error when running "make install":

 make[1]: *** [install-toolkit] Error 1

 How can this be fixed? Thank you! More error-related information comes here:

» make install
if test -d /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/gbench; then
make install-gbench;
else
make install-toolkit;
fi
make[1]: Entering directory /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++' /bin/rm -rf /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++ /bin/install -c -d /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/bin /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++ /bin/install -c /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/* /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/bin /bin/install -c -m 644 /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/*.* /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib if test -d /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi; then \ cp -pPR /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib/; \ fi rm -f /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib/lib*-static.a cd /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib && \ for x in *.a; do \ /bin/ln -s "$x" "/bin/basename "$x" .a-static.a"; \ done cd /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/include && find * -name CVS -prune -o -print |\ cpio -pd /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++ 51193 blocks /bin/install -c -m 644 /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/* /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++ /bin/install: omitting directory ‘/nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/common’ 
make[1]: *** [install-toolkit] 
Error 1 make[1]: Leaving directory/nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++'
make: *** [install] Error 2

**Comment by rmhubley** [comment]
Thanks for the report and sorry for the long delay.  I have not seen this error before. Do you have permissions to install files into /usr/local on this system? 

For instance can you do the following without getting an error message?:

% mkdir /usr/local/rmblast

If that's not the problem, I suggest we see if the error is coming from the RMBlast package or from the NCBI source code.  To do that you could download a fresh copy of the ncbi-blast-2.6.0+-src.tar.gz from NCBI and try building/installing it:

% cd ncbi-blast-2.6.0+-src/c++
% ./configure --with-mt --prefix=/usr/local/ncbi-blast --without-debug
% make
% make install

Let me know how it goes.

Cheers,

-R

**Comment by ponomarevsy** [comment]
Hi, Robert! Thanks for getting back on this issue. Even though the installation phase fails, the executables built seem to work just fine according to one of our users. So, I am ok with what we have at the moment...

» ls build/rmblast  
```                                       
bin  include  lib
```
» ls build/rmblast/bin                                     
```
aalookup_unit_test        blastsetup_unit_test         ntlookup_unit_test              search_strategy_unit_test
aascan_unit_test          blast_unit_test              ntscan_unit_test                seedtop
align_format_unit_test    blastx                       optionshandle_unit_test         segmasker
bdbloader_unit_test       convert2blastmask            phiblast_unit_test              seqdb_demo
bl2seq_unit_test          datatool                     prelimsearch_unit_test          seqdb_perf
blastdb_aliastool         deltablast                   project_tree_builder            seqdb_unit_test
blastdbcheck              delta_unit_test              psibl2seq_unit_test             seqinfosrc_unit_test
blastdbcmd                dustmasker                   psiblast                        seqsrc_unit_test
blastdbcp                 gapinfo_unit_test            psiblast_iteration_unit_test    setupfactory_unit_test
blastdb_format_unit_test  gencode_singleton_unit_test  psiblast_unit_test              split_query_unit_test
blastdiag_unit_test       gene_info_reader             pssmcreate_unit_test            stat_unit_test
blastengine_unit_test     gene_info_unit_test          pssmenginefreqratios_unit_test  subj_ranges_unit_test
blastextend_unit_test     hspfilter_besthit_unit_test  querydata_unit_test             tblastn
blastfilter_unit_test     hspfilter_culling_unit_test  queryinfo_unit_test             tblastx
blast_formatter           hspstream_unit_test          redoalignment_unit_test         tracebacksearch_unit_test
blast_format_unit_test    legacy_blast.pl              remote_blast_unit_test          traceback_unit_test
blasthits_unit_test       linkhsp_unit_test            rmblastn                        uniform_search_unit_test
blastinput_unit_test      magicblast_unit_test         rpsblast                        update_blastdb.pl
blastn                    makeblastdb                  rpstblastn                      version_reference_unit_test
blastoptions_unit_test    makembindex                  rps_unit_test                   windowmasker
blastp                    makeprofiledb                run_with_lock                   windowmasker_2.2.22_adapter.py
blast_services_unit_test  msa2pssm_unit_test           scoreblk_unit_test              writedb_unit_test
```

**Comment by AGI-admin** [comment]
I am getting this error too, running "make install" as root.  I did not use --prefix so it would install to standard location of /usr/local but root has full permission.  It seems to finish everything in the Makefile for "install-toolkit"  but still produces the error.  I tried to add "-v" flag for $(INSTALL) but it doesn't help explain what the error is.  It is problematic because i like to use "checkinstall" script since there is no uninstall rule in the Makefile, but checkinstall fails because "make install" fails.

**Comment by Farah-Nazir** [comment]
Hi! I am using BioPerl (v5.18.2) and the latest release of RMBlast (ncbi-blast-2.6.0+-src.tar.gz, with patch isb-2.6.0+-changes-vers2.patch.gz), The problem is; I am getting the following error upon running the command "make install":

make[1]: *** [install-toolkit] Error 1
make[1]: Leaving directory `/usr/local/rmblast/ncbi-blast-2.6.0+-src/c++'
make: *** [install] Error 2
![screenshot from 2018-03-21 15 46 53](https://user-images.githubusercontent.com/37241081/37706075-ff44fd32-2d1f-11e8-8244-a56224b65b16.png)

How can this be fixed?

**Comment by raviraut206** [comment]
****I am getting following error in installation process for RMBlast.** Please give your suggestions**

I fallowed the following steps..
1. Download RMBlast Source Package and Patch File:
ncbi-blast-2.6.0+-src.tar.gz
isb-2.6.0+-changes-vers2.patch.gz ( updated 3/29/17 - bugfix )
Unpack Distribution:
Unpack the distribution in your home directory or in a temporary location ( ie. /tmp ).
cd /mytmp/location/
tar zxvf ncbi-blast-2.6.0+-src.tar.gz
gunzip isb-2.6.0+-changes-vers2.patch.gz
2. Patch:
cd ncbi-blast-2.6.0+-src
patch -p1 < ../isb-2.6.0+-changes-vers2.patch
3. Build: 
To compile the programs for installation in /usr/local/rmblast run:
cd ncbi-blast-2.6.0+-src/c++
./configure --with-mt --prefix=/usr/local/rmblast --without-debug
make



 make install
if test -d /home/ravindraraut/Analysis/RepeatMasker/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/gbench; then \
    make  install-gbench; \
else \
    make  install-toolkit; \
fi
make[1]: Entering directory '/home/ravindraraut/Analysis/RepeatMasker/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++'
/bin/rm -rf /usr/local/rmblast/include/ncbi-tools++
/usr/bin/install -c -d /usr/local/rmblast/bin /usr/local/rmblast/lib /usr/local/rmblast/include/ncbi-tools++
/usr/bin/install: cannot create directory ‘/usr/local/rmblast’: Permission denied
/usr/bin/install: cannot create directory ‘/usr/local/rmblast’: Permission denied
/usr/bin/install: cannot create directory ‘/usr/local/rmblast’: Permission denied
Makefile:40: recipe for target 'install-toolkit' failed
make[1]: *** [install-toolkit] Error 1
make[1]: Leaving directory '/home/ravindraraut/Analysis/RepeatMasker/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++'
Makefile:62: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by AGI-admin** [comment]
/usr/local is only writable by system or admin account, therefore getting "Permission denied" error when trying to install from your user account.  Traditionally, the "make install" command need to be run as root or with sudo i.e. "sudo make install"

**Comment by raviraut206** [comment]
**Getting this error:**

usr/bin/g++ -std=gnu++11 -Wl,--enable-new-dtags -Wl,-export-dynamic -pthread -fopenmp -O3 -finline-functions -fstrict-aliasing -fomit-frame-pointer rmblastn_app.o -Wl,-rpath,/usr/local/rmblast/lib -Wl,-rpath-link,/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib -L/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib -lblast_app_util -lblastinput-static -lncbi_xloader_blastdb_rmt-static -lncbi_xloader_blastdb-static -lxblastformat-static -lalign_format-static -ltaxon1-static -lblastdb_format-static -lgene_info-static -lxformat-static -lxcleanup-static -lgbseq-static -lsubmit-static -lmlacli-static -lmla-static -lmedlars-static -lpubmed-static -lvalid-static -ltaxon3-static -lxalnmgr-static -lblastxml-static -lblastxml2-static -lxcgi-static -lxhtml-static -lxblast-static -lxalgoblastdbindex-static -lcomposition_adjustment-static -lxalgodustmask-static -lxalgowinmask-static -lseqmasks_io-static -lseqdb-static -lblast_services-static -lxalnmgr-static -lxobjutil-static -lxobjread-static -lvariation-static -lcreaders-static -lsubmit-static -lxnetblastcli-static -lxnetblast-static -lblastdb-static -lscoremat-static -ltables-static -lncbi_xloader_genbank-static -lncbi_xreader_id1-static -lncbi_xreader_id2-static -lncbi_xreader_cache-static -ldbapi_driver-static -lncbi_xreader-static -lxconnect-static -lid1-static -lid2-static -lxobjmgr-static -lgenome_collection-static -lseqedit-static -lseqsplit-static -lseqset-static -lseq-static -lseqcode-static -lsequtil-static -lpub-static -lmedline-static -lbiblio-static -lgeneral-static -lxser-static -lxutil-static -lxncbi-static -lxcompress-static -lz -lbz2 -ldl -lpcre -lssl -lcrypto -lnsl -ldl -lm -lpthread -o rmblastn
strip rmblastn
/bin/bash /home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/scripts/common/impl/if_diff.sh /bin/ln -f rmblastn /home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin
/bin/ln -f rmblastn /home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/rmblastn
make[4]: Leaving directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/app/rmblastn'
make[3]: Leaving directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/app/rmblastn'
NCBI_BUT_EXPENDABLE=' (but expendable)'  /usr/bin/make -C dblb -w  all_r  ||  exit 5
make[3]: Entering directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/app/dblb'
make[3]: Leaving directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/app/dblb'
NCBI_BUT_EXPENDABLE=' (but expendable)'  /usr/bin/make -C tls -w  all_r  ||  exit 5
make[3]: Entering directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/app/tls'
make[3]: Leaving directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/app/tls'
NCBI_BUT_EXPENDABLE=' (but expendable)'  /usr/bin/make -C idfetch -w  all_r  ||  exit 5
make[3]: Entering directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/app/idfetch'
make[3]: Leaving directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/app/idfetch'
make[2]: Leaving directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/app'
/usr/bin/make -C sample -w  all_r  ||  exit 5
make[2]: Entering directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/sample'
make[2]: Leaving directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/sample'
/usr/bin/make -C internal -w  all_r  ||  exit 5
make[2]: Entering directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/internal'
make[2]: Leaving directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build/internal'
make[1]: Leaving directory '/home/gnomeadmin/te_analysis/SequenceSearchEngine/RMBlast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/build'

**Comment by HHHit** [comment]
Can rmblast be installed in another directory? e.g. /home ?
