### ISSUE TITLE
Refiner::buildConsensus() Error

### ISSUE THREAD

**Issue by JFsanchezherrero** [rmhubley/RepeatModeler#7]
Dear @rmhubley,
I have tried several times to run RepeatModeler in my genome dataset and I keep on getting the same error when it gets to round-5. 
I have attached here an example of it. I run it three times and I got always the same error but different families id for each run.

###### Standard OUT:
Processing RECON family: 16432
  - Saving elements to a file...
    - 16 elements found.
Element Gathering: 00:00:00 (hh:mm:ss) Elapsed Time
Refining family-16432 model...
Refiner::buildConsensus(): /users/jfsanchez/DATA/RepeatModeler/RM_41217.ThuSep281827292017/round-5/family-16386.fa ( family-16386 ) didn't have any hsps!!!!!

###### Standard ERROR:

In file: /users/jfsanchez/RepeatModeler/RM_41217.ThuSep281827292017/round-5/summary/eles.  Ignoring line and moving on.
Can't call method "getNumAlignedSeqs" on an undefined value at /users/jfsanchez/RepeatModeler/RepeatModeler-open-1.0.10/Refiner line 706.
RepeatModeler: Could not open refined model /users/jfsanchez/DATA/RepeatModeler/RM_41217.ThuSep281827292017/round-5/family-16386.fa.refiner_cons!
######

The command I used is here:
# Database
BuildDatabase -engine ncbi -name myDraftGenome genome.scaffolds.fasta
# Search
RepeatModeler -database myDraftGenome -engine ncbi -pa 24

There were files consensi.fa & families.stk but they seem to be from round-4 according to time stamp of the file.

I manually classified the consensi sequences generated (1382 seqs) and the count of different repeats obtain were:
2 LTR...
105 LINE...
169 DNA.
1105 Unknown

I was expecting much bigger results so I assumed after round-5 they would increased.

Any ideas what is going on here? Do you think if I modify myselft the scripts (Refiner) and I just skip the step is failing here, final results would be strongly affected? 

Thanks,
Jose F.

**Comment by rmhubley** [comment]
Hi Jose,
  Thanks for the report.  There is not enough information here to definitively say what is happening.  If you don't mind, would you send me the screen output ( assuming you logged it ) and the raw results directory created by this run?  You can send it to rhubley@systemsbiology.org.  Also, which version of RMBlast and RECON are you using?  

RepeatModeler employs a random sampling strategy on the input sequence.  Re-running the program will produce slightly different results ( IDs, order of discovered families etc ).  If you desire a reproducible sample be used simply use the "-srand ####" option to seed the random number generator with the same value each time you run.  Finally, you state that you are surprised by the low number of families you found in this genome.  Could you elaborate on why you were surprised and what you were expecting?  

Thanks,

-R

**Comment by DjampaKozlowski** [comment]
Dear @JFsanchezherrero  and @rmhubley ,

I encounter exactly the same issue running RepeatModeler-1.0.10 with RMBlast-2.2.28 and RECON-1.08 : 
I'm currently running RepeatModeler over a dataset of 4 genomes of contigs using 4 files from a directory (1 fasta file per species, used option -DIR). My goal is to create a common TE library for 4 species (pretty close related), and then use it to mask each of the genomes.

(By the way, it is a proper way to realize this kind of analysis? Is this kind of analysis relevant ?)

Doing it, I encounter exactly the same issue as Jose (same standard-out and same standard error) with the difference the equivalent of the following line is missing in the SD-ERROR :
"In file: /users/jfsanchez/RepeatModeler/RM_41217.ThuSep281827292017/round-5/summary/eles. Ignoring line and moving on"

Googling my issue, I found the following blog (http://avrilomics.blogspot.fr/2015/02/finding-repeats-using-repeatmodeler.html) where it's written small sequences can leads to issues. So I filtered sequences and conserved the sequence larger than a threshold value. I did it for 5000 and 10000 threshold value but each time I encounter the same kind of issues.

I don't know if it is the good place to post my question. If it's not, I apologise. 

Thanks,
Djampa

**Comment by JFsanchezherrero** [comment]
Dear Djampa Kozlowski,
We finally sorted it out via email communication.

Basically, I sent him some files and he found a bug. He fixed it and release a new RepeatModeler release (1.0.11) that succesfully worked for me and solved the issue. I just donwloaded the new release and rerun my project. 

About the way you are doing these multi-genome repeat masking I wont be able to give you any guidance. @rmhubley should tell you further details.

Regards,
Jose

**Comment by DjampaKozlowski** [comment]
Dear @JFsanchezherrero ,

Thank you a lot for this quick answer! I'll try to download and run my analysis with the new RepeatModeler release as you advised and then I'll come back to both of you.

Thank you, I will wait for @rmhubley  answer about my strategy.

Thank you a lot Jose
Regards,
Djampa

**Comment by DjampaKozlowski** [comment]
Dear @JFsanchezherrero ,

It seems it worked! Thank you.

Best regards,
Djampa

**Comment by rmhubley** [comment]
Sorry for the delay in responding @DjampaKozlowski.  I am glad that 1.0.11 fixed the problem for you.   My primary concern related to your "combined" analysis is the possibility of missing low copy-number families.  RepeatModeler uses a sampling approach in it's discovery workflow.  If your individual genomes are large enough there is a possibility it will not obtain enough sample from a particular genome to detect low-copy repeats.

**Comment by DjampaKozlowski** [comment]
Dear @rmhubley,

Thank you for answering! Indeed the 1.0.11 version fixed my problems and I've been able to run several analysis.

Best regards,
Djampa

**Comment by pliang64** [comment]
Hi Everyone: I am getting a similar problem using 1.0.11 with the error message copied below.  I tried to search all files in the RepeatModuller folder, as well as the RepeatScout and RECON folders for "family-0.fa.refiner_cons", and I can only find places in RepeatModuller for reading the file, not for writing the file. So I don't know where the problem occurred based on the program generating the file. It could be generated by a binary file? Any help in solving this problem would be greatly appreciated.  Thanks. Ping

"....
Program duration is 543.0 sec = 9.1 min = 0.2 hr
   - Collecting repeat instances...
 -- Refining Family R=1672 / 0 ( RS Elements: 2445, Using 100 ):
RepeatModeler: Could not open refined model /local/pliang/lavender_RM/RM_107906.FriMay252207562018/round-1/family-0.fa.refiner_cons!

**Comment by rmhubley** [comment]
Hi there,

  Would you send me the file:  /local/pliang/lavender_RM/RM_107906.FriMay252207562018/round-1/family-0.fa so I may take a look?

Thanks,

-R

**Comment by pliang64** [comment]
Hi Robert,

Thank you for getting back to me. I’d really appreciate your help in solving the issue and be able to run it properly.  Attached is the family-0.fa file and the full log file. BTW, below is the list of the files in the round-1 folder and the command I used.

[pliang@cop33 lavender_RM]$ perl ~/labbin/RepeatModeler-open-1.0.11/RepeatModeler -pa 8 -database lavender4RM &>run_repeatmoduller.log2 &


[pliang@cop33 lavender_RM]$ ll RM_107906.FriMay252207562018/round-1/
total 134140
-rw-rw-r-- 1 pliang pliang   772648 May 25 22:20 consensi.fa
-rw-rw-r-- 1 pliang pliang        0 May 25 22:40 consensi-refined.fa
-rw-rw-r-- 1 pliang pliang    25613 May 25 22:40 family-0.fa
-rw-rw-r-- 1 pliang pliang        0 May 25 22:40 index.html
-rw-rw-r-- 1 pliang pliang      397 May 25 22:20 makeblastdb.log
-rw-rw-r-- 1 pliang pliang 51251893 May 25 22:10 sampleDB-1.fa
-rw-rw-r-- 1 pliang pliang 70686694 May 25 22:11 sampleDB-1.fa.lfreq
-rw-rw-r-- 1 pliang pliang   291946 May 25 22:20 sampleDB-1.fa.nhr
-rw-rw-r-- 1 pliang pliang    67132 May 25 22:20 sampleDB-1.fa.nin
-rw-rw-r-- 1 pliang pliang    44656 May 25 22:20 sampleDB-1.fa.nnd
-rw-rw-r-- 1 pliang pliang      220 May 25 22:20 sampleDB-1.fa.nni
-rw-rw-r-- 1 pliang pliang    22360 May 25 22:20 sampleDB-1.fa.nog
-rw-rw-r-- 1 pliang pliang 12616886 May 25 22:20 sampleDB-1.fa.nsq
-rw-rw-r-- 1 pliang pliang   775537 May 25 22:20 sampleDB-1.fa.rscons
-rw-rw-r-- 1 pliang pliang   772648 May 25 22:20 sampleDB-1.fa.rscons.filtered

Thank you again and I look forward to hearing back from you soon,
Ping


Ping Liang, PhD
Associate Professor, Canada Research Chair, and Graduate Program Director
Department of Biological Sciences
Brock University
St. Catharines, Ontario
Canada L2S 3A1

TEL: 905-688-5550 X 5922
FAX: 905-688-1855
EMail: pliang@brocku.ca<mailto:pliang@brocku.ca>


On May 29, 2018, at 4:47 PM, Robert Hubley <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

Would you send me the file: /local/pliang/lavender_RM/RM_107906.FriMay252207562018/round-1/family-0.fa so I may take a look?

Thanks,

-R

**Comment by Maulik23** [comment]
Hi @YuntaoTan, I also got the exact same error, did you mange to solve it?

Thank you. 

Regards,
Maulik
