### ISSUE TITLE
don't have consensi.fa.classified

### ISSUE THREAD

**Issue by linz-li** [rmhubley/RepeatModeler#9]
hi, 
When I  run RepeatModeler,  I didn't get the consensi.fa.classified file. I thought I didn't finish the program, so I use the `-recoverDir` . However, This directory ( path/to/my/work_dir ) appears to contain a successful run of RepeatModeler. But the output only have consensi.fa and families.stk file. I don't know what's wrong with  the RepeatModeler.

**Comment by rmhubley** [comment]
The latest version of RepeatModeler copies the final classified results from the RM_#########/ directory to the parent directory and renames them to <database_name>-families.stk and <database_name>-families.fa.  Do you have these files?  Do the family identifiers inside the files have the "#<class>/<subclass>" suffixes?  If not, then you can attempt to run the classification by hand on these files like so:

<RepeatModeler_path>/RepeatClassifier -consensi <work_dir>/consensi.fa -stockholm <work_dir>/families.stk

Let me know what you find.

-R

**Comment by linz-li** [comment]
I only get consensi.fa and families.stk file, don't have <database_name>-families.stk and <database_name>-families.fa file. I'll try the RepeatClassifier. Thank you very much !

**Comment by Shrihariprasad** [comment]
while running the RepeatClassifier it runs for nearly 50 minutes and an error saying missing RepeatMasker.lib.nsq appears

**Comment by jebrosen** [comment]
@Shrihariprasad That sounds unrelated to this issue, and is not a known problem with the latest versions of RepeatMasker or RepeatModeler. Please open a new issue for that question, including what versions of RepeatModeler and RepeatMasker you are using and the complete error message.
